# Generated by Django 3.0.4 on 2020-03-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='have_satellites',
            field=models.BooleanField(default=False),
        ),
    ]
