# Generated by Django 3.0.4 on 2020-03-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0002_auto_20200309_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='period',
            field=models.FloatField(),
        ),
    ]
