# Generated by Django 3.0.4 on 2020-03-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0003_auto_20200309_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.FloatField(),
        ),
    ]
